MethodLength:
  CountComments: false  # count full line comments?
  Max: 47

# Use only ascii symbols in comments.
AsciiComments:
  Enabled: false

AbcSize:
  Max: 71

CyclomaticComplexity:
  Max: 12

PerceivedComplexity:
  Max: 9

Security/JSONLoad:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

Style/Next:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Metrics/BlockLength:
  Max: 30
