MethodLength:
  CountComments: false  # count full line comments?
  Max: 47

# Use only ascii symbols in comments.
AsciiComments:
  Enabled: false

AbcSize:
  Max: 61

CyclomaticComplexity:
  Max: 11

PerceivedComplexity:
  Max: 9
